# Generated by Django 5.2.16 on 2026-07-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Turista')),
                ('contract_address', models.CharField(max_length=42, unique=True, verbose_name='Dirección del Contrato')),
                ('group_size', models.IntegerField(default=1, verbose_name='Número de Personas')),
                ('allergy', models.CharField(default='Ninguna', max_length=100, verbose_name='Alergias')),
                ('current_stage', models.IntegerField(default=0, verbose_name='Etapa Actual (0 a 6)')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Estado de la Experiencia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
    ]
